allowBuilds:
  '@github/keytar': true
  '@prisma/engines': true
  bcrypt: true
  esbuild: true
  node-pty: true
  prisma: true
  sharp: false
  unrs-resolver: false
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
